const test=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto'),fs=require('node:fs');
const {validateContent}=require('../dist/lib/content-schema.cjs');const handler=require('../dist/api/admin.js');const seed=JSON.parse(fs.readFileSync(__dirname+'/../dist/content.json'));
const password='test-only-long-password-2026',salt='0123456789abcdef0123456789abcdef';process.env.ADMIN_PASSWORD_HASH=salt+':'+crypto.scryptSync(password,salt,64).toString('hex');process.env.ADMIN_SESSION_SECRET='test-only-session-secret-32-characters-long';process.env.GITHUB_CONTENT_TOKEN='test-only';
async function req(method,body,cookie='',origin='https://www.topsolution.co.mz'){let status,data,headers={};await handler({method,body,headers:{origin,'content-type':'application/json',cookie,'x-forwarded-for':'127.0.0.1'}},{setHeader:(k,v)=>headers[k]=v,status:n=>{status=n;return{json:v=>data=v};}});return {status,data,headers};}
let cookie;
test('private API denies unauthenticated reads and writes',async()=>{assert.equal((await req('GET')).status,401);assert.equal((await req('POST',{action:'publish'})).status,401);});
test('cross-origin login is rejected',async()=>assert.equal((await req('POST',{action:'login',password},'','https://attacker.example')).status,403));
test('password verification and hardened signed session cookie',async()=>{assert.equal((await req('POST',{action:'login',password:'wrong'})).status,401);const result=await req('POST',{action:'login',password});assert.equal(result.status,200);cookie=result.headers['Set-Cookie'].split(';')[0];assert.match(result.headers['Set-Cookie'],/HttpOnly; Secure; SameSite=Strict/);assert.equal((await req('POST',{action:'publish'},cookie+'tampered')).status,401);});
test('schema rejects executable image paths, invalid prices, duplicates and links',()=>{for(const mutate of [c=>c.products[0].image='javascript:alert(1)',c=>c.products[0].price=-1,c=>c.products[0].price=1.123,c=>c.products.push(c.products[0]),c=>c.banners.push({title:'x',description:'',button:'go',href:'https://evil.example',image:''})]){const c=structuredClone(seed);mutate(c);assert.throws(()=>validateContent(c));}assert.equal(validateContent(seed).products.length,seed.products.length);});
test('publishing is atomic and refuses stale base commits',async()=>{const calls=[];const head='a'.repeat(40);global.fetch=async(url,options)=>{calls.push({url,options});let data;if(url.includes('/git/ref/heads/'))data={object:{sha:head}};else if(url.includes('/git/commits/')&&options.method==='GET')data={tree:{sha:'b'.repeat(40)}};else if(url.endsWith('/git/trees')){const tree=JSON.parse(options.body);assert.deepEqual(tree.tree.map(e=>e.path),['dist/content.json','dist/products.js']);assert.ok(tree.tree[1].content.includes('window.TOP_PRODUCTS'));data={sha:'c'.repeat(40)};}else if(url.endsWith('/git/commits'))data={sha:'d'.repeat(40)};else if(url.includes('/git/refs/heads/')){assert.equal(JSON.parse(options.body).force,false);data={};}else throw Error(url);return {ok:true,json:async()=>data};};const result=await req('POST',{action:'publish',base:head,content:seed,assets:[]},cookie);assert.equal(result.status,200);assert.equal(result.data.head,'d'.repeat(40));const writes=calls.filter(c=>c.options.method!=='GET');assert.equal(writes.length,3);calls.length=0;assert.equal((await req('POST',{action:'publish',base:'0'.repeat(40),content:seed},cookie)).status,409);assert.equal(calls.filter(c=>c.options.method!=='GET').length,0);});
test('logout expires session cookie and missing configuration fails closed',async()=>{assert.match((await req('POST',{action:'logout'},cookie)).headers['Set-Cookie'],/Max-Age=0/);delete process.env.GITHUB_CONTENT_TOKEN;assert.equal((await req('GET',null,cookie)).status,503);});
